using System;
using System.IO;
using System.Linq;
using System.Text;

namespace JSAI.WinApp
{
    public partial class MainForm
    {
        private bool SyncStoryboardVideoPreviewNodes(WorkflowNode storyboardVideoNode)
        {
            if (!string.Equals(storyboardVideoNode.Type, WorkflowNodeCatalog.StoryboardVideo, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            storyboardVideoNode.Params ??= new WorkflowNodeParameters();
            storyboardVideoNode.Params.EnsureDefaults(storyboardVideoNode.Type);

            var artifactPath = storyboardVideoNode.ArtifactPath;
            if (string.IsNullOrWhiteSpace(artifactPath) || !File.Exists(artifactPath))
            {
                return false;
            }

            var normalizedArtifactPath = Path.GetFullPath(artifactPath);
            var previewNodes = _document.Nodes
                .Where(node =>
                    string.Equals(node.Type, WorkflowNodeCatalog.VideoPreview, StringComparison.OrdinalIgnoreCase) &&
                    string.Equals(node.Params?.AutoGeneratedSourceNodeId, storyboardVideoNode.Id, StringComparison.OrdinalIgnoreCase))
                .OrderBy(node => node.Params?.AutoGeneratedSequence ?? int.MaxValue)
                .ToList();

            var targetPreviewNode = previewNodes.FirstOrDefault(node =>
                !string.IsNullOrWhiteSpace(node.ArtifactPath) &&
                File.Exists(node.ArtifactPath) &&
                string.Equals(Path.GetFullPath(node.ArtifactPath), normalizedArtifactPath, StringComparison.OrdinalIgnoreCase));

            var changed = false;
            if (targetPreviewNode == null)
            {
                var nextSequence = previewNodes.Count == 0
                    ? 1
                    : previewNodes.Max(node => Math.Max(1, node.Params?.AutoGeneratedSequence ?? 1)) + 1;

                targetPreviewNode = new WorkflowNode
                {
                    Id = _document.CreateNextNodeId(),
                    Type = WorkflowNodeCatalog.VideoPreview,
                    Params = new WorkflowNodeParameters
                    {
                        AutoGeneratedSourceNodeId = storyboardVideoNode.Id,
                        AutoGeneratedGroupKey = "storyboard-video-preview",
                        AutoGeneratedSequence = nextSequence,
                    },
                };
                targetPreviewNode.Params.EnsureDefaults(targetPreviewNode.Type);
                _document.Nodes.Add(targetPreviewNode);
                previewNodes.Add(targetPreviewNode);
                changed = true;
            }

            previewNodes = previewNodes
                .OrderBy(node => node.Params?.AutoGeneratedSequence ?? int.MaxValue)
                .ToList();

            var baseX = storyboardVideoNode.X + WorkflowNodeCard.StoryboardVideoCardWidth + 92;
            var baseY = storyboardVideoNode.Y + 18;

            for (var index = 0; index < previewNodes.Count; index++)
            {
                var previewNode = previewNodes[index];
                var sequence = Math.Max(1, previewNode.Params?.AutoGeneratedSequence ?? index + 1);
                var x = baseX;
                var y = baseY + index * (WorkflowNodeCard.VideoPreviewCardHeight + 18);

                if (ReferenceEquals(previewNode, targetPreviewNode))
                {
                    changed |= ApplyStoryboardVideoPreviewState(previewNode, storyboardVideoNode, x, y, sequence);
                }
                else
                {
                    changed |= AssignInt(() => previewNode.X, value => previewNode.X = value, x);
                    changed |= AssignInt(() => previewNode.Y, value => previewNode.Y = value, y);
                }

                if (_document.Edges.All(edge => edge.From != storyboardVideoNode.Id || edge.To != previewNode.Id))
                {
                    _document.Edges.Add(new WorkflowEdge
                    {
                        From = storyboardVideoNode.Id,
                        To = previewNode.Id,
                    });
                    changed = true;
                }
            }

            return changed;
        }

        private static bool ApplyStoryboardVideoPreviewState(
            WorkflowNode previewNode,
            WorkflowNode storyboardVideoNode,
            int x,
            int y,
            int sequence)
        {
            previewNode.Params ??= new WorkflowNodeParameters();
            previewNode.Params.EnsureDefaults(previewNode.Type);

            var changed = false;
            changed |= AssignString(() => previewNode.Type, value => previewNode.Type = value, WorkflowNodeCatalog.VideoPreview);
            changed |= AssignInt(() => previewNode.X, value => previewNode.X = value, x);
            changed |= AssignInt(() => previewNode.Y, value => previewNode.Y = value, y);
            changed |= AssignString(() => previewNode.ArtifactPath, value => previewNode.ArtifactPath = value, storyboardVideoNode.ArtifactPath ?? string.Empty);
            changed |= AssignString(() => previewNode.ArtifactKind, value => previewNode.ArtifactKind = value, "video");
            changed |= AssignString(
                () => previewNode.Output,
                value => previewNode.Output = value,
                BuildStoryboardVideoPreviewOutput(storyboardVideoNode, sequence));

            changed |= AssignString(
                () => previewNode.Params.Input,
                value => previewNode.Params.Input = value,
                storyboardVideoNode.Params?.StoryboardVideoPrompt ?? string.Empty);
            changed |= AssignString(
                () => previewNode.Params.AutoGeneratedSourceNodeId,
                value => previewNode.Params.AutoGeneratedSourceNodeId = value,
                storyboardVideoNode.Id);
            changed |= AssignString(
                () => previewNode.Params.AutoGeneratedGroupKey,
                value => previewNode.Params.AutoGeneratedGroupKey = value,
                "storyboard-video-preview");
            changed |= AssignInt(
                () => previewNode.Params.AutoGeneratedSequence,
                value => previewNode.Params.AutoGeneratedSequence = value,
                sequence);
            changed |= AssignString(
                () => previewNode.Params.CoreIdea,
                value => previewNode.Params.CoreIdea = value,
                string.IsNullOrWhiteSpace(storyboardVideoNode.Params?.StoryboardVideoModelFamily)
                    ? "视频结果"
                    : storyboardVideoNode.Params!.StoryboardVideoModelFamily.Trim());
            return changed;
        }

        private static string BuildStoryboardVideoPreviewOutput(WorkflowNode storyboardVideoNode, int sequence)
        {
            var builder = new StringBuilder();
            builder.AppendLine($"视频结果 #{sequence}");
            builder.AppendLine();

            if (!string.IsNullOrWhiteSpace(storyboardVideoNode.ArtifactPath))
            {
                builder.AppendLine($"文件路径：{storyboardVideoNode.ArtifactPath}");
            }

            if (storyboardVideoNode.Params != null)
            {
                builder.AppendLine($"视频接口：{WorkflowNodeParameters.GetStoryboardVideoPlatformDisplayName(storyboardVideoNode.Params.StoryboardVideoPlatform)}");
                builder.AppendLine($"主模型：{WorkflowNodeParameters.GetStoryboardVideoModelFamilyDisplayName(storyboardVideoNode.Params.StoryboardVideoModelFamily)}");
                builder.AppendLine($"子模型：{WorkflowNodeParameters.GetStoryboardVideoSubModelDisplayName(storyboardVideoNode.Params.StoryboardVideoSubModel)}");
                builder.AppendLine($"画幅：{storyboardVideoNode.Params.StoryboardVideoAspectRatio}");
                builder.AppendLine($"时长：{storyboardVideoNode.Params.StoryboardVideoDurationSeconds}秒");
                builder.AppendLine($"画质：{storyboardVideoNode.Params.StoryboardVideoQuality}");
                builder.AppendLine($"选中分镜：{storyboardVideoNode.Params.StoryboardVideoSelectedShotIds?.Count ?? 0}");
            }

            if (!string.IsNullOrWhiteSpace(storyboardVideoNode.Output))
            {
                builder.AppendLine();
                builder.AppendLine("节点输出：");
                builder.AppendLine(storyboardVideoNode.Output.Trim());
            }

            return builder.ToString().Trim();
        }
    }
}
