using System;
using System.Collections.Generic;
using System.Linq;

namespace JSAI.WinApp
{
    public partial class MainForm
    {
        private bool SyncCreativeDescriptionNodes(WorkflowNode scriptNode)
        {
            if (scriptNode.Type != WorkflowNodeCatalog.Script)
            {
                return false;
            }

            scriptNode.Params ??= new WorkflowNodeParameters();
            scriptNode.Params.EnsureDefaults(scriptNode.Type);

            var generatedEpisodes = scriptNode.Params.GeneratedScriptEpisodes ?? new List<GeneratedScriptEpisode>();
            var existingNodes = _document.Nodes
                .Where(node =>
                    node.Type == WorkflowNodeCatalog.CreativeDescription &&
                    string.Equals(node.Params?.AutoGeneratedSourceNodeId, scriptNode.Id, StringComparison.OrdinalIgnoreCase))
                .OrderBy(node => node.Params?.AutoGeneratedSequence ?? int.MaxValue)
                .ToList();

            var changed = false;
            var activeNodeIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var startX = scriptNode.X + WorkflowNodeCard.ScriptCardWidth + 92;
            var startY = scriptNode.Y;
            var verticalGap = WorkflowNodeCard.CreativeCardHeight + 26;
            var groupKey = BuildCreativeGroupKey(scriptNode);

            for (var index = 0; index < generatedEpisodes.Count; index++)
            {
                var episode = generatedEpisodes[index];
                var sequence = index + 1;
                var creativeNode = existingNodes.FirstOrDefault(node => (node.Params?.AutoGeneratedSequence ?? 0) == sequence);
                if (creativeNode == null)
                {
                    creativeNode = new WorkflowNode
                    {
                        Id = _document.CreateNextNodeId(),
                        Type = WorkflowNodeCatalog.CreativeDescription,
                        Params = new WorkflowNodeParameters
                        {
                            PreferredModelId = GetDefaultModelIdForNodeType(WorkflowNodeCatalog.CreativeDescription),
                        },
                    };
                    creativeNode.Params.EnsureDefaults(creativeNode.Type);
                    _document.Nodes.Add(creativeNode);
                    existingNodes.Add(creativeNode);
                    changed = true;
                }

                activeNodeIds.Add(creativeNode.Id);
                changed |= ApplyCreativeNodeState(
                    creativeNode,
                    scriptNode,
                    episode,
                    groupKey,
                    sequence,
                    startX,
                    startY + (index * verticalGap));

                if (_document.Edges.All(edge => edge.From != scriptNode.Id || edge.To != creativeNode.Id))
                {
                    _document.Edges.Add(new WorkflowEdge
                    {
                        From = scriptNode.Id,
                        To = creativeNode.Id,
                    });
                    changed = true;
                }
            }

            foreach (var obsoleteNode in existingNodes.Where(node => !activeNodeIds.Contains(node.Id)).ToList())
            {
                _document.Nodes.Remove(obsoleteNode);
                _document.Edges.RemoveAll(edge => edge.From == obsoleteNode.Id || edge.To == obsoleteNode.Id);
                changed = true;
            }

            return changed;
        }

        private static bool ApplyCreativeNodeState(
            WorkflowNode creativeNode,
            WorkflowNode scriptNode,
            GeneratedScriptEpisode episode,
            string groupKey,
            int sequence,
            int x,
            int y)
        {
            creativeNode.Params ??= new WorkflowNodeParameters();
            creativeNode.Params.EnsureDefaults(creativeNode.Type);

            var changed = false;
            var normalizedCreativeOutput = WorkflowExecutor.NormalizeTextResult(WorkflowNodeCatalog.CreativeDescription, episode.Content);
            var creativeOutputChanged = !string.Equals(
                WorkflowExecutor.NormalizeTextResult(WorkflowNodeCatalog.CreativeDescription, creativeNode.Output),
                normalizedCreativeOutput,
                StringComparison.Ordinal);
            changed |= AssignString(() => creativeNode.Type, value => creativeNode.Type = value, WorkflowNodeCatalog.CreativeDescription);
            changed |= AssignInt(() => creativeNode.X, value => creativeNode.X = value, x);
            changed |= AssignInt(() => creativeNode.Y, value => creativeNode.Y = value, y);
            changed |= AssignString(
                () => creativeNode.Output,
                value => creativeNode.Output = value,
                normalizedCreativeOutput);
            changed |= AssignString(() => creativeNode.ArtifactPath, value => creativeNode.ArtifactPath = value, string.Empty);
            changed |= AssignString(() => creativeNode.ArtifactKind, value => creativeNode.ArtifactKind = value, string.Empty);

            changed |= AssignString(() => creativeNode.Params.Input, value => creativeNode.Params.Input = value, string.Empty);
            changed |= AssignString(
                () => creativeNode.Params.ScriptSourceChapter,
                value => creativeNode.Params.ScriptSourceChapter = value,
                scriptNode.Params?.ScriptSourceChapter ?? string.Empty);
            changed |= AssignString(
                () => creativeNode.Params.AutoGeneratedSourceNodeId,
                value => creativeNode.Params.AutoGeneratedSourceNodeId = value,
                scriptNode.Id);
            changed |= AssignString(
                () => creativeNode.Params.AutoGeneratedGroupKey,
                value => creativeNode.Params.AutoGeneratedGroupKey = value,
                groupKey);
            changed |= AssignInt(
                () => creativeNode.Params.AutoGeneratedSequence,
                value => creativeNode.Params.AutoGeneratedSequence = value,
                sequence);
            changed |= AssignString(
                () => creativeNode.Params.CoreIdea,
                value => creativeNode.Params.CoreIdea = value,
                episode.Title ?? string.Empty);

            if (creativeOutputChanged && creativeNode.Params.StoryboardShots.Count > 0)
            {
                creativeNode.Params.StoryboardShots.Clear();
                changed = true;
            }

            return changed;
        }

        private static string BuildCreativeGroupKey(WorkflowNode scriptNode)
        {
            var chapter = scriptNode.Params?.ScriptSourceChapter?.Trim();
            return string.IsNullOrWhiteSpace(chapter) ? "script" : chapter;
        }

        private static bool AssignInt(Func<int> getter, Action<int> setter, int value)
        {
            if (getter() == value)
            {
                return false;
            }

            setter(value);
            return true;
        }

        private static bool AssignString(Func<string> getter, Action<string> setter, string value)
        {
            value ??= string.Empty;
            if (string.Equals(getter(), value, StringComparison.Ordinal))
            {
                return false;
            }

            setter(value);
            return true;
        }
    }
}
