using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;

namespace JSAI.WinApp
{
    public sealed class VideoCollectionSourceItem
    {
        public string ArtifactPath { get; init; } = string.Empty;

        public string DisplayName { get; init; } = string.Empty;

        public string SourceNodeId { get; init; } = string.Empty;

        public string SourceNodeType { get; init; } = string.Empty;

        public int Sequence { get; init; }

        public string ThumbnailPath { get; init; } = string.Empty;

        public string Summary { get; init; } = string.Empty;

        public string DurationLabel { get; init; } = string.Empty;

        public int DurationSeconds { get; init; }
    }

    public static class VideoCollectionSupport
    {
        public static List<VideoCollectionSourceItem> CollectSources(WorkflowDocument document, WorkflowNode node)
        {
            if (document == null || node == null)
            {
                return new List<VideoCollectionSourceItem>();
            }

            var items = new List<VideoCollectionSourceItem>();
            var seenPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var order = 0;
            node.Params ??= new WorkflowNodeParameters();
            node.Params.EnsureDefaults(node.Type);
            var upstreamNodes = WorkflowExecutor.CollectUpstreamNodes(document, node);

            foreach (var upstream in upstreamNodes)
            {
                if (string.Equals(upstream.Type, WorkflowNodeCatalog.StoryboardVideo, StringComparison.OrdinalIgnoreCase))
                {
                    upstream.Params ??= new WorkflowNodeParameters();
                    upstream.Params.EnsureDefaults(upstream.Type);
                    foreach (var generatedClip in (upstream.Params.StoryboardVideoGeneratedClips ?? new List<StoryboardVideoGeneratedClip>())
                                 .Where(clip => !string.IsNullOrWhiteSpace(clip.ArtifactPath) && File.Exists(clip.ArtifactPath))
                                 .OrderBy(clip => Math.Max(1, clip.ShotNumber)))
                    {
                        AddGeneratedStoryboardVideoClip(items, seenPaths, upstream, generatedClip, ref order);
                    }

                    var previewNodes = document.Nodes
                        .Where(candidate =>
                            string.Equals(candidate.Type, WorkflowNodeCatalog.VideoPreview, StringComparison.OrdinalIgnoreCase) &&
                            string.Equals(candidate.Params?.AutoGeneratedSourceNodeId, upstream.Id, StringComparison.OrdinalIgnoreCase))
                        .OrderBy(candidate => candidate.Params?.AutoGeneratedSequence ?? int.MaxValue)
                        .ToList();

                    foreach (var previewNode in previewNodes)
                    {
                        AddSourceItem(items, seenPaths, previewNode, upstream, ref order);
                    }
                }

                WorkflowNode? ownerNode = null;
                if (string.Equals(upstream.Type, WorkflowNodeCatalog.VideoPreview, StringComparison.OrdinalIgnoreCase) &&
                    !string.IsNullOrWhiteSpace(upstream.Params?.AutoGeneratedSourceNodeId))
                {
                    ownerNode = document.Nodes.FirstOrDefault(candidate =>
                        string.Equals(candidate.Id, upstream.Params.AutoGeneratedSourceNodeId, StringComparison.OrdinalIgnoreCase));
                }

                AddSourceItem(items, seenPaths, upstream, ownerNode, ref order);
            }

            AddImportedVideoAssets(items, seenPaths, node, ref order);

            return items
                .OrderBy(item => item.Sequence)
                .ToList();
        }

        public static List<VideoCollectionSourceItem> GetSelectedSources(WorkflowDocument document, WorkflowNode node)
        {
            node.Params ??= new WorkflowNodeParameters();
            node.Params.EnsureDefaults(node.Type);

            var sources = CollectSources(document, node);
            if (sources.Count == 0)
            {
                node.Params.VideoCollectionSelectedArtifactPaths.Clear();
                node.Params.VideoCollectionCurrentArtifactPath = string.Empty;
                node.Params.VideoCollectionSelectionInitialized = false;
                return sources;
            }

            var selectedPaths = new HashSet<string>(
                (node.Params.VideoCollectionSelectedArtifactPaths ?? new List<string>())
                    .Where(path => !string.IsNullOrWhiteSpace(path)),
                StringComparer.OrdinalIgnoreCase);

            if (selectedPaths.Count == 0 && !node.Params.VideoCollectionSelectionInitialized)
            {
                selectedPaths = new HashSet<string>(sources.Select(item => item.ArtifactPath), StringComparer.OrdinalIgnoreCase);
            }

            var selectedSources = sources
                .Where(item => selectedPaths.Contains(item.ArtifactPath))
                .ToList();
            node.Params.VideoCollectionSelectionInitialized = true;

            node.Params.VideoCollectionSelectedArtifactPaths = selectedSources
                .Select(item => item.ArtifactPath)
                .ToList();

            SyncTimelineClips(node, sources, selectedSources);

            if (!selectedSources.Any(item =>
                    string.Equals(item.ArtifactPath, node.Params.VideoCollectionCurrentArtifactPath, StringComparison.OrdinalIgnoreCase)))
            {
                node.Params.VideoCollectionCurrentArtifactPath = selectedSources.FirstOrDefault()?.ArtifactPath
                    ?? sources[0].ArtifactPath;
            }

            return selectedSources;
        }

        public static List<VideoCollectionSourceItem> GetTimelineSources(WorkflowDocument document, WorkflowNode node)
        {
            var selectedSources = GetSelectedSources(document, node);
            if (selectedSources.Count == 0 || node.Params == null)
            {
                return selectedSources;
            }

            var byPath = selectedSources
                .GroupBy(item => item.ArtifactPath, StringComparer.OrdinalIgnoreCase)
                .ToDictionary(group => group.Key, group => group.First(), StringComparer.OrdinalIgnoreCase);

            var ordered = new List<VideoCollectionSourceItem>();
            foreach (var clip in node.Params.VideoCollectionTimelineClips ?? new List<VideoCollectionTimelineClip>())
            {
                if (!clip.Enabled || string.IsNullOrWhiteSpace(clip.ArtifactPath))
                {
                    continue;
                }

                var normalizedPath = NormalizePath(clip.ArtifactPath);
                if (byPath.TryGetValue(normalizedPath, out var source) &&
                    !ordered.Any(item => string.Equals(item.ArtifactPath, source.ArtifactPath, StringComparison.OrdinalIgnoreCase)))
                {
                    ordered.Add(source);
                }
            }

            foreach (var source in selectedSources)
            {
                if (!ordered.Any(item => string.Equals(item.ArtifactPath, source.ArtifactPath, StringComparison.OrdinalIgnoreCase)))
                {
                    ordered.Add(source);
                }
            }

            return ordered;
        }

        private static void SyncTimelineClips(
            WorkflowNode node,
            IReadOnlyList<VideoCollectionSourceItem> allSources,
            IReadOnlyList<VideoCollectionSourceItem> selectedSources)
        {
            node.Params ??= new WorkflowNodeParameters();
            var selectedPaths = new HashSet<string>(
                selectedSources.Select(item => item.ArtifactPath),
                StringComparer.OrdinalIgnoreCase);
            var sourceByPath = allSources
                .GroupBy(item => item.ArtifactPath, StringComparer.OrdinalIgnoreCase)
                .ToDictionary(group => group.Key, group => group.First(), StringComparer.OrdinalIgnoreCase);

            var next = new List<VideoCollectionTimelineClip>();
            var added = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var clip in node.Params.VideoCollectionTimelineClips ?? new List<VideoCollectionTimelineClip>())
            {
                var normalizedPath = NormalizePath(clip.ArtifactPath);
                if (string.IsNullOrWhiteSpace(normalizedPath) ||
                    !selectedPaths.Contains(normalizedPath) ||
                    !sourceByPath.TryGetValue(normalizedPath, out var source) ||
                    !added.Add(normalizedPath))
                {
                    continue;
                }

                next.Add(new VideoCollectionTimelineClip
                {
                    ArtifactPath = source.ArtifactPath,
                    Enabled = true,
                    Caption = KeepSimplifiedChineseVisibleTextOnly(clip.Caption),
                });
            }

            foreach (var source in selectedSources)
            {
                if (!added.Add(source.ArtifactPath))
                {
                    continue;
                }

                next.Add(new VideoCollectionTimelineClip
                {
                    ArtifactPath = source.ArtifactPath,
                    Enabled = true,
                    Caption = KeepSimplifiedChineseVisibleTextOnly(source.Summary),
                });
            }

            node.Params.VideoCollectionTimelineClips = next;
        }

        private static string NormalizePath(string path)
        {
            if (string.IsNullOrWhiteSpace(path))
            {
                return string.Empty;
            }

            try
            {
                return Path.GetFullPath(path);
            }
            catch
            {
                return path.Trim();
            }
        }

        private static void AddGeneratedStoryboardVideoClip(
            ICollection<VideoCollectionSourceItem> items,
            ISet<string> seenPaths,
            WorkflowNode sourceNode,
            StoryboardVideoGeneratedClip clip,
            ref int order)
        {
            var normalizedPath = Path.GetFullPath(clip.ArtifactPath);
            if (!seenPaths.Add(normalizedPath))
            {
                return;
            }

            order++;
            items.Add(new VideoCollectionSourceItem
            {
                ArtifactPath = normalizedPath,
                DisplayName = $"视频片段 #{Math.Max(1, clip.ShotNumber)}",
                SourceNodeId = sourceNode.Id,
                SourceNodeType = sourceNode.Type,
                Sequence = order,
                ThumbnailPath = File.Exists(clip.ReferenceImagePath) ? clip.ReferenceImagePath : ResolveThumbnailPath(sourceNode),
                Summary = string.IsNullOrWhiteSpace(clip.Scene)
                    ? $"第{Math.Max(1, clip.ShotNumber)}镜"
                    : KeepSimplifiedChineseVisibleTextOnly(clip.Scene).OrDefault($"第{Math.Max(1, clip.ShotNumber)}镜"),
                DurationLabel = $"{Math.Max(1, clip.DurationSeconds)}秒",
                DurationSeconds = Math.Max(1, clip.DurationSeconds),
            });
        }

        private static void AddSourceItem(
            ICollection<VideoCollectionSourceItem> items,
            ISet<string> seenPaths,
            WorkflowNode sourceNode,
            WorkflowNode? ownerNode,
            ref int order)
        {
            var artifactPath = (sourceNode.ArtifactPath ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(artifactPath) || !File.Exists(artifactPath))
            {
                return;
            }

            if (!string.Equals(sourceNode.ArtifactKind, "video", StringComparison.OrdinalIgnoreCase) &&
                !string.Equals(sourceNode.Type, WorkflowNodeCatalog.StoryboardVideo, StringComparison.OrdinalIgnoreCase) &&
                !string.Equals(sourceNode.Type, WorkflowNodeCatalog.VideoPreview, StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            var normalizedPath = Path.GetFullPath(artifactPath);
            if (!seenPaths.Add(normalizedPath))
            {
                return;
            }

            order++;

            var referenceNode = ownerNode ?? sourceNode;
            var thumbnailPath = ResolveThumbnailPath(referenceNode);
            var durationSeconds = Math.Max(
                1,
                referenceNode.Params?.StoryboardVideoDurationSeconds
                    ?? sourceNode.Params?.StoryboardVideoDurationSeconds
                    ?? 0);

            items.Add(new VideoCollectionSourceItem
            {
                ArtifactPath = normalizedPath,
                DisplayName = BuildDisplayName(sourceNode, ownerNode, order),
                SourceNodeId = referenceNode.Id,
                SourceNodeType = referenceNode.Type,
                Sequence = order,
                ThumbnailPath = thumbnailPath,
                Summary = BuildSummary(sourceNode, referenceNode),
                DurationLabel = $"{durationSeconds}秒",
                DurationSeconds = durationSeconds,
            });
        }

        private static void AddImportedVideoAssets(
            ICollection<VideoCollectionSourceItem> items,
            ISet<string> seenPaths,
            WorkflowNode node,
            ref int order)
        {
            node.Params ??= new WorkflowNodeParameters();
            node.Params.EnsureDefaults(node.Type);

            foreach (var asset in node.Params.VideoCollectionImportedAssets ?? new List<VideoCollectionImportedAsset>())
            {
                if (!string.Equals(asset.Kind, "video", StringComparison.OrdinalIgnoreCase) ||
                    string.IsNullOrWhiteSpace(asset.FilePath) ||
                    !File.Exists(asset.FilePath))
                {
                    continue;
                }

                var normalizedPath = Path.GetFullPath(asset.FilePath);
                if (!seenPaths.Add(normalizedPath))
                {
                    continue;
                }

                order++;
                var displayName = string.IsNullOrWhiteSpace(asset.DisplayName)
                    ? Path.GetFileNameWithoutExtension(normalizedPath)
                    : asset.DisplayName.Trim();

                items.Add(new VideoCollectionSourceItem
                {
                    ArtifactPath = normalizedPath,
                    DisplayName = string.IsNullOrWhiteSpace(displayName) ? $"导入视频 #{order}" : displayName,
                    SourceNodeId = node.Id,
                    SourceNodeType = "本地导入",
                    Sequence = order,
                    ThumbnailPath = string.Empty,
                    Summary = "本地导入视频素材",
                    DurationLabel = $"{Math.Max(1, asset.DurationSeconds)}秒",
                    DurationSeconds = Math.Max(1, asset.DurationSeconds),
                });
            }
        }

        private static string BuildDisplayName(WorkflowNode sourceNode, WorkflowNode? ownerNode, int order)
        {
            if (string.Equals(sourceNode.Type, WorkflowNodeCatalog.VideoPreview, StringComparison.OrdinalIgnoreCase) &&
                ownerNode != null)
            {
                var sequence = Math.Max(1, sourceNode.Params?.AutoGeneratedSequence ?? order);
                return $"视频片段 #{sequence}";
            }

            if (string.Equals(sourceNode.Type, WorkflowNodeCatalog.StoryboardVideo, StringComparison.OrdinalIgnoreCase))
            {
                return $"分镜视频 #{order}";
            }

            return $"{sourceNode.Type} #{order}";
        }

        private static string BuildSummary(WorkflowNode sourceNode, WorkflowNode referenceNode)
        {
            var output = WorkflowExecutor.NormalizeTextResult(referenceNode.Type, sourceNode.Output ?? referenceNode.Output ?? string.Empty);
            if (string.IsNullOrWhiteSpace(output))
            {
                return Path.GetFileName(sourceNode.ArtifactPath);
            }

            var firstLine = output
                .Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(line => line.Trim())
                .FirstOrDefault(line => !string.IsNullOrWhiteSpace(line));

            return string.IsNullOrWhiteSpace(firstLine)
                ? Path.GetFileName(sourceNode.ArtifactPath)
                : KeepSimplifiedChineseVisibleTextOnly(firstLine).OrDefault("视频片段");
        }

        private static string KeepSimplifiedChineseVisibleTextOnly(string? text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return string.Empty;
            }

            var filtered = Regex.Replace(text, @"\[[^\]]*\]", string.Empty);
            filtered = Regex.Replace(filtered, @"[A-Za-z0-9_./\\:@#%&+=*<>|~`^$]+", string.Empty);
            filtered = Regex.Replace(filtered, @"[^\u3400-\u4DBF\u4E00-\u9FFF，。！？、：；“”‘’（）《》【】—…\s]", string.Empty);
            filtered = Regex.Replace(filtered, @"\s+", " ").Trim();
            return Regex.IsMatch(filtered, @"[\u3400-\u4DBF\u4E00-\u9FFF]") ? filtered : string.Empty;
        }

        private static string ResolveThumbnailPath(WorkflowNode node)
        {
            node.Params ??= new WorkflowNodeParameters();
            node.Params.EnsureDefaults(node.Type);

            if (!string.IsNullOrWhiteSpace(node.Params.StoryboardVideoFusedImagePath) &&
                File.Exists(node.Params.StoryboardVideoFusedImagePath))
            {
                return node.Params.StoryboardVideoFusedImagePath;
            }

            var selectedIds = new HashSet<string>(
                node.Params.StoryboardVideoSelectedShotIds ?? Enumerable.Empty<string>(),
                StringComparer.OrdinalIgnoreCase);

            var preferredShot = (node.Params.StoryboardShots ?? new List<StoryboardShot>())
                .FirstOrDefault(shot =>
                    !string.IsNullOrWhiteSpace(shot.SplitImagePath) &&
                    File.Exists(shot.SplitImagePath) &&
                    (selectedIds.Count == 0 || selectedIds.Contains(shot.Id)));

            if (preferredShot != null)
            {
                return preferredShot.SplitImagePath;
            }

            preferredShot = (node.Params.StoryboardShots ?? new List<StoryboardShot>())
                .FirstOrDefault(shot => !string.IsNullOrWhiteSpace(shot.SplitImagePath) && File.Exists(shot.SplitImagePath));

            return preferredShot?.SplitImagePath ?? string.Empty;
        }
    }
}
